### Save fx spot market data to cosmos db example
POST localhost:7006/api/SaveDocumentToDb?datatype=price.spot&assetClass=fx&schemaversion=1.0.0
Content-Type: application/json

{
    "price": 1.11,
    "id": "price.spot__fx__EURUSD__ny__2025-05-14__official",
    "schemaVersion": "1.0.0",
    "assetId": "EURUSD",
    "assetClass": "fx",
    "dataType": "price.spot",
    "region": "ny",
    "tags": [
        "spot"
    ],
    "documentType": "official",
    "createTimestamp": "2025-05-13T00:09:12.4071054+00:00",
    "asOfDate": "2025-05-14",
    "asOfTime": "15:30:05"
}

### Save crypto ordinal spot price data to cosmos db example
POST localhost:7006/api/SaveDocumentToDb?datatype=price.ordinals.spot&assetClass=crypto&schemaversion=1.0.0
Content-Type: application/json

{
  "price": 1.11,
  "id": "price.ordinals.spot__crypto__quantum_cats_1__global__2025-05-14__official",
  "schemaVersion": "1.0.0",
  "assetId": "quantum_cats_1",
  "assetClass": "crypto",
  "dataType": "price.ordinals.spot",
  "region": "global",
  "tags": [
    "spot"
  ],
  "documentType": "official",
  "createTimestamp": "2025-05-13T00:09:12.4071054+00:00",
  "asOfDate": "2025-05-14",
  "inscriptionNumber": 77777,
  "inscriptionId": "12345",
  "parentInscriptionId": "1234",
  "collectionName": "quantum cats"
}