@host = localhost:7006

### Save fx spot market data to cosmos db example
POST {{host}}/api/SaveDocumentToDb?datatype=price.spot&assetClass=fx&schemaversion=1.0.0
Content-Type: application/json

{
    "price": 1.09,
    "side": "mid",
    "schemaVersion": "1.0.0",
    "assetId": "eurusd",
    "assetClass": "fx",
    "dataType": "price.spot",
    "region": "ny",
    "tags": [
        "spot"
    ],
    "documentType": "official",
    "asOfDate": "2025-05-13",
    "asOfTime": "15:30:05"
}

### Save crypto ordinal spot price data to cosmos db example
POST {{host}}/api/SaveDocumentToDb?datatype=price.ordinals.spot&assetClass=crypto&schemaversion=1.0.0
Content-Type: application/json

{
  "price": 1.13,
  "currency": "btc",
  "side": "bid",
  "schemaVersion": "1.0.0",
  "assetId": "quantum_cats_1",
  "assetClass": "crypto",
  "dataType": "price.ordinals.spot",
  "region": "global",
  "tags": [
    "spot"
  ],
  "documentType": "official",
  "asOfDate": "2025-05-13",
  "inscriptionNumber": 77777,
  "inscriptionId": "12345",
  "parentInscriptionId": "1234",
  "collectionName": "quantum cats"
}