name: Update Guidelines Timestamp

on:
  push:
    branches: [main]
    paths:
      - ".aiguidance/ai-guidelines.md"

# Add explicit permissions for security
permissions:
  contents: write # Required to commit and push changes

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Update timestamp
        run: node scripts/update-guidelines.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .aiguidance/ai-guidelines.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update AI guidelines timestamp [skip ci]" && git push)
